# Generated by Django 5.0.3 on 2024-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('ape_paterno', models.CharField(max_length=15)),
                ('ape_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('mail', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('num_movil', models.IntegerField(max_length=9, unique=True)),
                ('activo', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
