# Generated by Django 5.0.3 on 2024-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_movil',
            field=models.IntegerField(unique=True),
        ),
    ]
